title: Activate History Channel on Your Device
description: Are you aware that you can watch your favourite show on history.com? The first step is to use a web browser to navigate to the history.com/activate web initiation page.
theme: jekyll-theme-cayman
